services:
  api:
    container_name: "helpdesk_app_api"
    volumes:
      - ./src/helpdesk_app_backend:/helpdesk_app_backend
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    environment:
      - PYTHONPATH=/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  db:
    container_name: "helpdesk_app_db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
